### ISSUE TITLE
I think we need a better button for accessing the different messages

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/windows-phone-app#1]
If you want, I can see could Sona design something for it. 

iOS has tap-to-change, which works really nicely (although lacks a little in discoverability, so we may have to go with a tooltip). Is that possible in Windows? 

But if not, a more obvious image might be the way forward. Let me know if you need something designed.

**Comment by theothernt** [comment]
Agreed about the icon, I could implement the tap-to-change method the iOS app uses and see how that goes. Worst case, we can come up with another icon for the button.

**Comment by canuckjacq** [comment]
if you think you can implement the tap-to-change, that would be amazing. If not, I can get Sona to design a button.

**Comment by theothernt** [comment]
The badge will now change when tapped (with a nice bounce animation), like the iOS version.
